# =========================
# Local profile
# =========================

# --- Datasource (?? 1: ?? MySQL) ---
spring.datasource.url=jdbc:mysql://localhost:3306/characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- Datasource (?? 2: H2 ???) ---
# spring.datasource.url=jdbc:h2:mem:hr;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
# spring.datasource.driver-class-name=org.h2.Driver
# spring.h2.console.enabled=true

# --- Hikari (?? ?? ???) ---
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# --- Logging: ??? ? ?? ---
logging.level.root=DEBUG
logging.level.org.springframework.web=DEBUG
