# =========================
# Prod profile
# =========================


# SSM(Parameter Store)?? ??? ??
spring.config.import=aws-parameterstore:/haruharu/db_prod
spring.cloud.aws.region.static=ap-northeast-2

# ??/????(???? ??)
logging.level.root=INFO
logging.level.org.springframework.web=ERROR
logging.level.com.woosan.hr_system=DEBUG

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5