# =========================
# Prod profile
# =========================

# --- AWS ---
# SSM(Parameter Store)
spring.config.import=aws-parameterstore:/haruharu/db_prod/


logging.level.root=INFO
logging.level.org.springframework.web=ERROR
logging.level.com.woosan.hr_system=DEBUG

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5